############################
# STEP 1 build executable binary
############################
FROM golang:1.13-alpine AS builder

RUN apk update && apk add --no-cache git ca-certificates tzdata && update-ca-certificates

WORKDIR /src

COPY /src/go.mod /src/go.sum ./

RUN go mod download
RUN go mod verify

COPY /src ./

RUN go get -u github.com/swaggo/swag/cmd/swag
RUN swag init -g cmd/api/api.go -o ./docs

# Build the binary.
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./go/bin/api cmd/api/api.go

############################
# STEP 2 build a small image
############################

FROM scratch

# Copy our static executable.
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd

COPY --from=builder /src/config /config
COPY --from=builder /src/docs ./docs

COPY --from=builder /src/go/bin/api .
